"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Building2, Filter, Plus, Search, UsersRound } from "lucide-react";
import { Badge, Button, Card, Field, MetricCard, Modal, PageHeader, inputClass } from "@/components/ui";
import { useNoraStore } from "@/lib/store";
import { formatCurrency } from "@/lib/utils";

export function CustomersPage() {
  const customers = useNoraStore((s) => s.customers);
  const [query, setQuery] = useState(""); const [open, setOpen] = useState(false);
  const filtered = useMemo(() => customers.filter((c) => `${c.name}${c.contact}${c.tags.join("")}`.includes(query)), [customers, query]);
  return <><PageHeader title="客户中心" description="统一维护客户档案、标签与履约关系" actions={<Button onClick={() => setOpen(true)}><Plus size={16} />新建客户</Button>} />
    <div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="有效客户" value={String(customers.filter(c => c.status === "active").length)} suffix="家" icon={UsersRound} /><MetricCard label="重点客户" value="2" suffix="家" icon={Building2} tone="purple" /><MetricCard label="本月销售额" value="119.6" suffix="万元" icon={UsersRound} tone="success" change="较上月 +12.8%" /><MetricCard label="待审核" value={String(customers.filter(c => c.status === "pending").length)} suffix="家" icon={Filter} tone="warning" /></div>
    <Card className="overflow-hidden"><div className="flex flex-wrap gap-3 border-b border-[#e8edf3] p-4"><div className="relative flex-1 min-w-[220px]"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#8995aa]" /><input value={query} onChange={e => setQuery(e.target.value)} className={`${inputClass} pl-9`} placeholder="搜索客户、联系人或标签" /></div><Button variant="secondary"><Filter size={15} />筛选</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="bg-[#fafbfd] text-[11px] text-[#8792a6]"><tr><th className="px-5 py-3">客户</th><th className="px-5 py-3">分类与标签</th><th className="px-5 py-3">联系人</th><th className="px-5 py-3">结算</th><th className="px-5 py-3">订单/销售额</th><th className="px-5 py-3">状态</th></tr></thead><tbody>{filtered.map(c => <tr key={c.id} className="border-t border-[#edf0f4] hover:bg-[#fbfcfe]"><td className="px-5 py-4"><Link href={`/customers/${c.id}`} className="font-semibold text-[#263451] hover:text-[#1768f2]">{c.name}</Link><p className="mt-1 font-mono text-[11px] text-[#8a95a8]">{c.code}</p></td><td className="px-5 py-4"><div className="flex gap-1"><Badge tone="info">{c.type}</Badge>{c.tags.map(t => <Badge key={t}>{t}</Badge>)}</div></td><td className="px-5 py-4 text-sm text-[#4e5d77]">{c.contact}<p className="text-xs text-[#8a95a8]">{c.phone}</p></td><td className="px-5 py-4 text-sm text-[#56647d]">{c.settlement}</td><td className="px-5 py-4 text-sm text-[#31405c]">{c.orderCount} 笔<p className="text-xs text-[#8692a6]">{formatCurrency(c.revenue)}</p></td><td className="px-5 py-4"><Badge tone={c.status === "active" ? "success" : "warning"}>{c.status === "active" ? "已启用" : "待审核"}</Badge></td></tr>)}</tbody></table></div></Card>
    <Modal open={open} onOpenChange={setOpen} title="新建客户" description="建立客户档案后可录入订单" footer={<><Button variant="secondary" onClick={() => setOpen(false)}>取消</Button><Button onClick={() => setOpen(false)}>保存并提交审核</Button></>}><div className="grid gap-4 sm:grid-cols-2"><Field label="客户名称" required><input className={inputClass} placeholder="请输入企业或机构名称" /></Field><Field label="客户分类"><select className={inputClass}><option>A类</option><option>B类</option><option>C类</option></select></Field><Field label="联系人" required><input className={inputClass} placeholder="姓名" /></Field><Field label="联系电话" required><input className={inputClass} placeholder="手机号码" /></Field><Field label="配送地址"><input className={inputClass} placeholder="详细地址" /></Field><Field label="结算方式"><select className={inputClass}><option>月结30天</option><option>月结45天</option><option>现结</option></select></Field></div></Modal>
  </>;
}
